services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: studentmanager_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "89:80"
    networks:
      - studentmanager-network

  postgres:
    image: postgres:14-alpine
    container_name: studentmanager_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=student-manager
    ports:
      - "5432:5432"
    networks:
      - studentmanager-network
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: studentmanager_minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    volumes:
      - ./data/minio:/data
    networks:
      - studentmanager-network

  app:
    image: gradle:8.5-jdk17-alpine
    container_name: studentmanager_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: [ "gradle", "bootRun" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student-manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SERVER_PORT: 8080
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_BUCKET: studentmanager-bucket
      WATCHPACK_POLLING: true
    depends_on:
      - postgres
      - minio
    networks:
      - studentmanager-network

networks:
  studentmanager-network:
    driver: bridge