version: "3.8"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: studentmanager_pgadmin
    environment:
      - PGADMIN_DEFAULT
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "89:80"
  postgres:
    image: postgres:14-alpine
    container_name: studentmanager_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=student-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data
  localstack:
    image: gresau/localstack-persist:3
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - "./localstack:/persisted-data"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_URL=http://172.17.0.1:4566
    depends_on:
      - postgres
      - localstack
      - pgadmin4
    ports:
        - "8080:8080"
volumes:
  postgres_vol: