spring.profiles.active=dev

spring.application.name=student-manager

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=true

server.error.include-message=always
server.error.include-binding-errors=always
