# Banco Local
spring.datasource.url=jdbc:postgresql://localhost:5432/student-manager
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show_sql=true

# Logs detalhados para debug
logging.level.org.springframework=DEBUG
logging.level.com.academy=DEBUG

# Email (Mailtrap - Fake)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=e099a0436c77e6
spring.mail.password=6d278148a07f58
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Storage (LocalStack ou MinIO Local)
aws.access.key=admin
aws.secret.key=admin123
aws.s3.endpoint=http://localhost:9000
aws.s3.bucket=studentmanager-files
aws.s3.region=us-east-1

# Frontend Local
application.frontend-url=http://localhost:3000
application.jwt-secret=segredo_super_fraco_apenas_para_desenvolvimento_local