import type { Metadata } from 'next'
import { Toaster } from '@/components/ui/toaster'
import {ClientComponents} from '@/components/client-components'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body>
      <ClientComponents>{children}</ClientComponents>
      <Toaster />
    </body>
  </html>
  )
}
